fix the previous commit, var is not always a variable, it may be an integer
It was breaking github/update-operations.sh with the error:

  Traceback (most recent call last):
    File "bin/sgqlc-codegen", line 33, in <module>
      sys.exit(load_entry_point('sgqlc', 'console_scripts', 'sgqlc-codegen')())
    File "sgqlc/codegen/__init__.py", line 51, in main
      args.func(args)
    File "sgqlc/codegen/operation.py", line 746, in handle_command
      gen.write()
    File "sgqlc/codegen/operation.py", line 628, in write
      self.write_operations()
    File "sgqlc/codegen/operation.py", line 645, in write_operations
      self.write_operation(source)
    File "sgqlc/codegen/operation.py", line 655, in write_operation
      for kind, name, code in visit(gql, visitor):
    File "graphql/language/visitor.py", line 314, in visit
      result = visit_fn(node, key, parent, path, ancestors)
    File "sgqlc/codegen/operation.py", line 470, in leave_field
      self.validate_required_arguments(node)
    File "sgqlc/codegen/operation.py", line 460, in validate_required_arguments
      if var.name in required:
  AttributeError: 'int' object has no attribute 'name'