__getattr__ should only fail silently with AttributeError
Until 3.7 this worked, but since 3.8 it's failing since `ValueError`
(caused in the scalar selection dir()) wasn't caught:

Failed example:
    for name in dir(repository.issues.number()): # no fields for scalar
        if not name.startswith('_'):
            print(name)
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest sgqlc.operation[138]>", line 1, in <module>
        for name in dir(repository.issues.number()): # no fields for scalar
      File "/home/runner/work/sgqlc/sgqlc/sgqlc/operation/__init__.py", line 1285, in __dir__
        original_dir = super(Selection, self).__dir__()
      File "/home/runner/work/sgqlc/sgqlc/sgqlc/operation/__init__.py", line 1302, in __getattr__
        return self[name]
      File "/home/runner/work/sgqlc/sgqlc/sgqlc/operation/__init__.py", line 1308, in __getitem__
        raise ValueError('Field %r of %s is not a container type.' %
    ValueError: Field number: Int! of Issue is not a container type.